### ISSUE TITLE
100% Game thread usage

### ISSUE THREAD

**Issue by Syntax3rror404** [ArmainAP/Unreal-Engine-Software-Occlusion-Culling#3]
After the task graph removal it doesn't crash anymore but it now runs worse then without this software culling. We need to make it back run in its own thread to not block the game thread.

**Comment by ArmainAP** [comment]
I am already on it, that a temporary solution as I did not noticed much impact on my scene/CPU, but it would make sense to have way worse performance on Arm/heavy scenes.

**Comment by Syntax3rror404** [comment]
> I am already on it, that a temporary solution as I did not noticed much impact on my scene/CPU, but it would make sense to have way worse performance on Arm/heavy scenes.

No, you also have this new bottleneck on powerfull pcs (AMD 7950X3D) with a simple scene. For example my test level also have distance cull but with 100 movable objects, because its a VR game. With software culling enabled the gamethread takes 11ms, without software culling it takes 3ms. So also on editor you cannot reach the 120fps anymore. 

In unreal engine 4 with software culling the gamethread also takes 3ms.
So to have culling running on its own thread makes sense. I think this is also the point why epic use the task graph for this. 

On ARM it doesnt run because you cannot compile in Shipping configuration.

**Comment by ArmainAP** [comment]
That is weird. I was testing on Intel 10900K with the FPS template scene. 

> In unreal engine 4 with software culling the gamethread also takes 3ms.
> So to have culling running on its own thread makes sense. I think this is also the point why epic use the task graph for this.

Yep, still working on bringing it back. 

> On ARM it doesnt run because you cannot compile in Shipping configuration.

I will take a look over this as well. I assumed it got fixed the previous issues.

**Comment by ArmainAP** [comment]
Hello! Sorry for the delay, I got quite caught up with Ludum Dare 56 and other projects. 

I have now committed 65534fe32b3a257d2a5a3cccb287f8e4979d0274 which bring back the Task Graph and fixes the previously experienced crash,. 

Can you confirm that it is working as expected?

**Comment by ArmainAP** [comment]
I also fixed the packaging error for Shipping configuration in commit 5e7157215ae3e4ffe04411c5f58bf247353e3eae

**Comment by Syntax3rror404** [comment]
Thank you for updating!!! Now it looks that its not crashing but it doesnt reduce any prims. Do you added a setting to enable the system which defaulted false?

**Comment by ArmainAP** [comment]
Hello, it should be enabled by default as usual. 

Did you have any settings before in Project Settings regarding the Software Occlusion Culling? If yes, those settings might have been reverted.

**Comment by Syntax3rror404** [comment]
> Hello, it should be enabled by default as usual.
> 
> Did you have any settings before in Project Settings regarding the Software Occlusion Culling? If yes, those settings might have been reverted.

I dont see any plugin settings from software culling. It seems like it is not working. If I hide behind a wall nothing change

**Comment by ArmainAP** [comment]
I guess the check that I added to avoid the crash made the culling not be granular enough to make an impact anymore. I fixed that now in commit 55446049fe3f26fabeb7ec36deddfbff5c8c0acb

Regarding the settings, I just renamed things a bit. Can you confirm that if you search "All Settings" for "Software Occlusion" you do not see this? If not, sounds like the plugin is not enabled. 
![image](https://github.com/user-attachments/assets/523d7c0e-8b48-4efd-acbd-094d98a40527)

**Comment by ArmainAP** [comment]
It has been a while so I am closing this down. If you encounter any further problems, feel free to open a new issue!
